---
title: "Detection per site"
author: "Vicky"
date: "1 11 2021"
output: html_document
---
  
```{r include = FALSE}
library("here")
library("conflicted")
library("readxl")
library("rgdal")
library("tidyverse")
library("ggplot2")
library("ggridges")
library("hrbrthemes")
library("magrittr")
library("viridis")
library("RColorBrewer")
library("tidytext")
library("cowplot")
library("grid")
library("plotly")

#load data:       #read csv file Version 1! version2 would be better, where is it?

bdata <- read.csv(here("bird_classification_v1","bird_classification_v1.csv"), check.names=TRUE,sep=",")


#Function for dopdownmenu
get_menu_list <- function(names){
  n_names = length(names)
  buttons = vector("list",n_names)
  
  for(i in seq_along(buttons)){
    buttons[i] = list(list(method = "restyle",
                           args = list("transforms[0].value", names[i]),
                           label = names[i]))
  }
  
  return_list = list(
    list(
      type = 'dropdown',
      active = 0,
      buttons = buttons
    )
  )
  
  return(return_list)
}

#Bubbleplot  edge lenght and grassland proportion  with  Detection per Site as size/color 
#dropdown menu to choose the species
p <- bdata %>%  dplyr::filter(Rank==1,) %>%
  #dplyr::filter(Common.Name== species,) %>% 
  dplyr::select("Site","Common.Name","permanent_grassland_proportion","edge_length_m","date") %>% 
  group_by(Site, Common.Name) %>% mutate(numocc = length((Common.Name)) ) %>%
  distinct(Common.Name , Site, .keep_all= TRUE) %>%
  plot_ly( type = 'scatter',
           x = ~permanent_grassland_proportion,
           y =~edge_length_m, 
           text =  ~paste('Site ', Site,':', numocc),
           hoverinfo = 'text',
           mode = "markers",
           size = ~numocc,
           color = ~numocc,
           # sizes = c(1, 24),
           #marker = list( opacity = 0.5,sizemode = 'diameter'),
           #hier
           transforms = list(
             list(
               type = 'filter',
               target = ~Common.Name,
               operation = '=',
               value = unique(bdata$Common.Name)[1]
             )
           )) %>% plotly::layout(title = "Detection per site" ,xaxis = list(title = 'Permanent grassland proportion (%)'),yaxis = list(title = 'Edge length (m)'),
                                 updatemenus = get_menu_list(unique(bdata$Common.Name)))


```


```{r, out.width="100%",fig.dim = c(5, 8)}
p

```

